/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab23;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author K4RK1N
 */
public class arayuz extends javax.swing.JFrame {

    /**
     * @return the dugumlerbilgi
     */
    public String[][] dugumlerbilgi;
    String baslangicNode;
    String bitisNode;
    boolean altkisma_gecis = false;
    int dugumsayisi = 0;

    /**
     * Creates new form panel
     */
    public arayuz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hatTablosu = new javax.swing.JTable();
        HatBasiText = new javax.swing.JTextField();
        HatSonuText = new javax.swing.JTextField();
        HatKapasiteText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tabloMesaji = new javax.swing.JLabel();
        toplamNodesayis_label = new javax.swing.JLabel();
        DsayisiText = new javax.swing.JTextField();
        baslangicNode_label = new javax.swing.JLabel();
        BDugumText = new javax.swing.JTextField();
        boruhattıBaslik_label = new javax.swing.JLabel();
        OlusturButon = new javax.swing.JButton();
        ResetButon = new javax.swing.JButton();
        DuzenleButon = new javax.swing.JButton();
        SDugumText = new javax.swing.JTextField();
        bitisNode_label = new javax.swing.JLabel();
        tabloMesaji2 = new javax.swing.JLabel();
        graphbilgileriBaslik_label = new javax.swing.JLabel();
        GoruntuleButon = new javax.swing.JButton();
        EkleButon = new javax.swing.JButton();
        SilButon = new javax.swing.JButton();
        graphMesaji = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HAVUZ PROBLEMİ");
        setLocation(new java.awt.Point(350, 75));

        hatTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Başlangıç Düğümü", "Bitiş Düğümü", "Kapasite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hatTablosu.setRowHeight(20);
        hatTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hatTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hatTablosu);

        HatBasiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HatBasiTextActionPerformed(evt);
            }
        });

        tabloMesaji.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tabloMesaji.setForeground(new java.awt.Color(255, 0, 0));
        tabloMesaji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        toplamNodesayis_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        toplamNodesayis_label.setText("Toplam Düğüm Sayısı");

        DsayisiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DsayisiTextActionPerformed(evt);
            }
        });

        baslangicNode_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        baslangicNode_label.setText("Başlangıç Düğümü");

        BDugumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDugumTextActionPerformed(evt);
            }
        });

        boruhattıBaslik_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boruhattıBaslik_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boruhattıBaslik_label.setText("Boru Hattı Bilgileri");

        OlusturButon.setBackground(new java.awt.Color(136, 189, 0));
        OlusturButon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OlusturButon.setForeground(new java.awt.Color(0, 0, 0));
        OlusturButon.setText("OLUŞTUR");
        OlusturButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlusturButonActionPerformed(evt);
            }
        });

        ResetButon.setBackground(new java.awt.Color(136, 189, 0));
        ResetButon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ResetButon.setForeground(new java.awt.Color(0, 0, 0));
        ResetButon.setText("RESET");
        ResetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButonActionPerformed(evt);
            }
        });

        DuzenleButon.setBackground(new java.awt.Color(136, 189, 0));
        DuzenleButon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DuzenleButon.setForeground(new java.awt.Color(0, 0, 0));
        DuzenleButon.setText("DÜZENLE");
        DuzenleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuzenleButonActionPerformed(evt);
            }
        });

        SDugumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDugumTextActionPerformed(evt);
            }
        });

        bitisNode_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bitisNode_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bitisNode_label.setText("Bitiş Düğümü");

        tabloMesaji2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tabloMesaji2.setForeground(new java.awt.Color(255, 0, 0));
        tabloMesaji2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        graphbilgileriBaslik_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        graphbilgileriBaslik_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        graphbilgileriBaslik_label.setText("Graph Bilgileri");

        GoruntuleButon.setBackground(new java.awt.Color(136, 189, 0));
        GoruntuleButon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GoruntuleButon.setForeground(new java.awt.Color(0, 0, 0));
        GoruntuleButon.setText("GÖRÜNTÜLE");
        GoruntuleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoruntuleButonActionPerformed(evt);
            }
        });

        EkleButon.setBackground(new java.awt.Color(136, 189, 0));
        EkleButon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EkleButon.setForeground(new java.awt.Color(0, 0, 0));
        EkleButon.setText("EKLE");
        EkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleButonActionPerformed(evt);
            }
        });

        SilButon.setBackground(new java.awt.Color(136, 189, 0));
        SilButon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SilButon.setForeground(new java.awt.Color(0, 0, 0));
        SilButon.setText("SİL");
        SilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilButonActionPerformed(evt);
            }
        });

        graphMesaji.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        graphMesaji.setForeground(new java.awt.Color(255, 0, 0));
        graphMesaji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(GoruntuleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(graphMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(DsayisiText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(toplamNodesayis_label))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BDugumText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(baslangicNode_label))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SDugumText)
                                    .addComponent(bitisNode_label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(graphbilgileriBaslik_label, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResetButon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OlusturButon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(HatBasiText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(HatSonuText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(HatKapasiteText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boruhattıBaslik_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DuzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tabloMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tabloMesaji2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)))
                                .addGap(75, 75, 75))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(graphbilgileriBaslik_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bitisNode_label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(baslangicNode_label)
                                .addComponent(toplamNodesayis_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SDugumText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DsayisiText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BDugumText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(OlusturButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addComponent(graphMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(boruhattıBaslik_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HatKapasiteText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HatSonuText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HatBasiText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(EkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(DuzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(SilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(GoruntuleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(tabloMesaji2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabloMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HatBasiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HatBasiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HatBasiTextActionPerformed

    private void BDugumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDugumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDugumTextActionPerformed

    private void DuzenleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuzenleButonActionPerformed
        // TODO add your handling code here:
        tabloMesaji.setText("");
        tabloMesaji2.setText("");
        DefaultTableModel tablo = (DefaultTableModel) hatTablosu.getModel();
        int secilen_satir = hatTablosu.getSelectedRow();

        if (secilen_satir == -1) {

            if (hatTablosu.getRowCount() == 0) {
                tabloMesaji2.setText("UYARI:");
                tabloMesaji.setText("Boru Hattı Bigileri Tablosu Boş");
            } else {
                tabloMesaji2.setText("UYARI:");
                tabloMesaji.setText("Düzenlenecek Boru Hattını Seçilmedi");
            }

        } else {

            tablo.setValueAt(HatBasiText.getText().toUpperCase(), secilen_satir, 0);
            tablo.setValueAt(HatSonuText.getText().toUpperCase(), secilen_satir, 1);
            tablo.setValueAt(HatKapasiteText.getText(), secilen_satir, 2);

            tabloMesaji.setText("Boru Hattı Düzenlendi");

        }
    }//GEN-LAST:event_DuzenleButonActionPerformed

    private void SDugumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDugumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SDugumTextActionPerformed

    private void OlusturButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlusturButonActionPerformed
        // TODO add your handling code here:

        graphMesaji.setText("");
        if (DsayisiText.getText().trim().equals("") || BDugumText.getText().trim().equals("") || SDugumText.getText().trim().equals("")) {

            if (SDugumText.getText().trim().equals("")) {
                graphMesaji.setText("UYARI:Bitiş Düğümü Boş Bırakılamaz");
            }
            if (BDugumText.getText().trim().equals("")) {
                graphMesaji.setText("UYARI:Başlangıç Düğümü Boş Bırakılamaz");
            }
            if (DsayisiText.getText().trim().equals("")) {
                graphMesaji.setText("UYARI:Toplam Düğüm Sayısı Boş Bırakılamaz");
            }

        } else {
            altkisma_gecis = true;
            dugumsayisi = Integer.parseInt(DsayisiText.getText());
            System.out.print(dugumsayisi + " ");

            baslangicNode = BDugumText.getText().toUpperCase();
            bitisNode = SDugumText.getText().toUpperCase();
            System.out.print(baslangicNode + " ");
            System.out.println(bitisNode + " ");
            System.out.println("=========");

        }


    }//GEN-LAST:event_OlusturButonActionPerformed

    private void ResetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButonActionPerformed

    private void DsayisiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DsayisiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DsayisiTextActionPerformed

    private void GoruntuleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoruntuleButonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel tablo = (DefaultTableModel) hatTablosu.getModel();
        String[][] dugumlerbilgi = new String[tablo.getRowCount()][3];

        for (int i = 0; i < dugumlerbilgi.length; i++) {
            for (int j = 0; j < 3; j++) {
                dugumlerbilgi[i][j] = tablo.getValueAt(i, j).toString();

            }
        }

        for (int i = 0; i < dugumlerbilgi.length; i++) {
            for (int j = 0; j < 3; j++) {
                System.out.print(dugumlerbilgi[i][j] + " ");
            }
            System.out.println(" ");
        }
        System.out.println("=========");
        int kenarsayisi = tablo.getRowCount();

        this.setVisible(false);
        new arayuzGraph(dugumlerbilgi, baslangicNode, bitisNode, dugumsayisi, kenarsayisi).setVisible(true);

    }//GEN-LAST:event_GoruntuleButonActionPerformed

    private void EkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleButonActionPerformed
        // TODO add your handling code here:
        //System.out.println(dugumsayisi);
        tabloMesaji.setText("");
        tabloMesaji2.setText("");
        DefaultTableModel tablo = (DefaultTableModel) hatTablosu.getModel();

        if (altkisma_gecis == true) {
            if (HatBasiText.getText().trim().equals("") || HatSonuText.getText().trim().equals("") || HatKapasiteText.getText().trim().equals("")) {

                if (HatKapasiteText.getText().trim().equals("")) {
                    tabloMesaji2.setText("UYARI:");
                    tabloMesaji.setText("Hat Kapisitesi Boş Bırakılamaz");
                }
                if (HatSonuText.getText().trim().equals("")) {
                    tabloMesaji2.setText("UYARI:");
                    tabloMesaji.setText("Hat Bitiş Düğümü Boş Bırakılamaz");
                }
                if (HatBasiText.getText().trim().equals("")) {
                    tabloMesaji2.setText("UYARI:");
                    tabloMesaji.setText("Hat Başlangıç Düğümü Boş Bırakılamaz");
                }

            } else {
                Object[] tabloyaEklenecekler = {HatBasiText.getText().toUpperCase(), HatSonuText.getText().toUpperCase(), HatKapasiteText.getText()};
                tablo.addRow(tabloyaEklenecekler);

            }
        } else {
            tabloMesaji2.setText("UYARI:");
            tabloMesaji.setText("Öncelikle Graph Bilgileri Girilmeli");
        }


    }//GEN-LAST:event_EkleButonActionPerformed

    private void SilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilButonActionPerformed
        // TODO add your handling code here:
        tabloMesaji.setText("");
        tabloMesaji2.setText("");
        DefaultTableModel tablo = (DefaultTableModel) hatTablosu.getModel();
        int secilen_satir = hatTablosu.getSelectedRow();

        if (secilen_satir == -1) {

            if (hatTablosu.getRowCount() == 0) {
                tabloMesaji2.setText("UYARI:");
                tabloMesaji.setText("Boru Hattı Bigileri Tablosu Boş");
            } else {
                tabloMesaji2.setText("UYARI:");
                tabloMesaji.setText("Silinecek Boru Hattını Seçilmedi");
            }

        } else {

            tablo.removeRow(secilen_satir);
            tabloMesaji.setText("Boru Hattı Silindi");

        }
    }//GEN-LAST:event_SilButonActionPerformed

    private void hatTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hatTablosuMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tablo = (DefaultTableModel) hatTablosu.getModel();
        int secilen_satir = hatTablosu.getSelectedRow();

        HatBasiText.setText(tablo.getValueAt(secilen_satir, 0).toString());
        HatSonuText.setText(tablo.getValueAt(secilen_satir, 1).toString());
        HatKapasiteText.setText(tablo.getValueAt(secilen_satir, 2).toString());


    }//GEN-LAST:event_hatTablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                arayuz arayuz = new arayuz();
                arayuz.setVisible(true);
                arayuz.setResizable(false);
                arayuz.setFocusable(false);
                arayuz.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                /*grafik.requestFocus();
                grafik.setFocusable(true);
                grafik.setFocusTraversalKeysEnabled(false);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BDugumText;
    private javax.swing.JTextField DsayisiText;
    private javax.swing.JButton DuzenleButon;
    private javax.swing.JButton EkleButon;
    private javax.swing.JButton GoruntuleButon;
    private javax.swing.JTextField HatBasiText;
    private javax.swing.JTextField HatKapasiteText;
    private javax.swing.JTextField HatSonuText;
    private javax.swing.JButton OlusturButon;
    private javax.swing.JButton ResetButon;
    private javax.swing.JTextField SDugumText;
    private javax.swing.JButton SilButon;
    private javax.swing.JLabel baslangicNode_label;
    private javax.swing.JLabel bitisNode_label;
    private javax.swing.JLabel boruhattıBaslik_label;
    private javax.swing.JLabel graphMesaji;
    private javax.swing.JLabel graphbilgileriBaslik_label;
    private javax.swing.JTable hatTablosu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tabloMesaji;
    private javax.swing.JLabel tabloMesaji2;
    private javax.swing.JLabel toplamNodesayis_label;
    // End of variables declaration//GEN-END:variables
}
